### ISSUE TITLE
“ecc_manager”  module

### ISSUE THREAD

**Issue by llhe110** [pulp-platform/dyn_spm#3]
（1）Is there a register instruction for this module？
I want to know how to use the register function inside

**Comment by micprog** [comment]
The ecc manager is from the redundancy cells repository and repeatedly instantiates the registers linked in [this header file](https://github.com/pulp-platform/redundancy_cells/blob/6a011b6f5acf3eca202ed847d6c64474a0bc7cb5/rtl/ecc_wrap/ECC.h) with a starting offset of `0x20`.

**Comment by llhe110** [comment]
Thank you very much for your guidance. I understand.
